In [5]:
# saving loss data and itrations into excel file

import torch
import torch.nn as nn
import torch.optim as optim

# Define XOR data
X = torch.tensor([[0.21,0.21], [0.18, 0.12], [0.15, 0.10], [0.12, 0.08],[0.10, 0.07],[0.08,0.06],[0.07, 0.05],[0.05, 0.04],[0.04, 0.03],[0.03, 0.02]], dtype=torch.float32)
y = torch.tensor([[1], [2], [3], [4],[5],[6],[7],[8],[9],[10]], dtype=torch.float32)
no_of_itration=[]
list_of_loss=[]
# Define the neural network model
class XORModel(nn.Module):
    def __init__(self):
        super(XORModel, self).__init__()
        self.hidden = nn.Linear(2, 4)  # 2 input features, 4 hidden units
        self.output = nn.Linear(4, 10)  # 1 output unit

    def forward(self, x):
        xh = torch.sigmoid(self.hidden(x))
        xo = (self.output(xh))
        return xo

# Instantiate the model, define the loss function and optimizer
model = XORModel()
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

# Training loop
epochs = 10000
for epoch in range(epochs):
    optimizer.zero_grad()
    outputs = model(X)
    loss = criterion(outputs, y)
    loss.backward()
    optimizer.step()

    if epoch % 500 == 0:
        print(f'Epoch [{epoch}/{epochs}], Loss: {loss.item():.4f}')
        list_of_loss.append(loss.item())
        no_of_itration.append(epoch)

# Testing the model
with torch.no_grad():
    predicted = model(X)
    print("Predicted outputs:\n", predicted.round())


Epoch [0/10000], Loss: 37.1738
Epoch [500/10000], Loss: 5.4006
Epoch [1000/10000], Loss: 1.0137
Epoch [1500/10000], Loss: 0.1561
Epoch [2000/10000], Loss: 0.0532
Epoch [2500/10000], Loss: 0.0299
Epoch [3000/10000], Loss: 0.0205
Epoch [3500/10000], Loss: 0.0158
Epoch [4000/10000], Loss: 0.0132
Epoch [4500/10000], Loss: 0.0117
Epoch [5000/10000], Loss: 0.0108
Epoch [5500/10000], Loss: 0.0102
Epoch [6000/10000], Loss: 0.0099
Epoch [6500/10000], Loss: 0.0096
Epoch [7000/10000], Loss: 0.0094
Epoch [7500/10000], Loss: 0.0092
Epoch [8000/10000], Loss: 0.0091
Epoch [8500/10000], Loss: 0.0089
Epoch [9000/10000], Loss: 0.0088
Epoch [9500/10000], Loss: 0.0087
Predicted outputs:
 tensor([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,

In [8]:
import tensorflow as tf

# Define XOR data
X = tf.constant([[0.21,0.21], [0.18, 0.12], [0.15, 0.10], [0.12, 0.08],[0.10, 0.07],[0.08,0.06],[0.07, 0.05],[0.05, 0.04],[0.04, 0.03],[0.03, 0.02]], dtype=tf.float32)
y = tf.constant([[1], [2], [3], [4],[5],[6],[7],[8],[9],[10]], dtype=tf.float32)
tf_no_of_itration=[]
tf_list_of_loss = []
# Define the neural network model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(4, input_shape=(2,), activation='sigmoid'),  # 4 hidden units
    tf.keras.layers.Dense(1)  # 1 output unit
])
# Compile the model
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.1), loss='mse')
# Custom callback to print the loss every 500 epochs
class PrintLoss(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
        if epoch % 500 == 0:
            print(f"Epoch {epoch}, Loss: {logs['loss']:.4f}")
            tf_no_of_itration.append(epoch)
            tf_list_of_loss.append(logs['loss'])
# Train the model with the custom callback
model.fit(X, y, epochs=10000, verbose=0, callbacks=[PrintLoss()])
# Testing the model
predicted = model.predict(X)
print("\nPredicted outputs:\n", tf.round(predicted))

C:\Users\qasim\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 0, Loss: 40.5354
Epoch 500, Loss: 0.1556
Epoch 1000, Loss: 0.0364
Epoch 1500, Loss: 0.0159
Epoch 2000, Loss: 0.0105
Epoch 2500, Loss: 0.0088
Epoch 3000, Loss: 0.0083
Epoch 3500, Loss: 0.0081
Epoch 4000, Loss: 0.0080
Epoch 4500, Loss: 0.0079
Epoch 5000, Loss: 0.0079
Epoch 5500, Loss: 0.0079
Epoch 6000, Loss: 0.0078
Epoch 6500, Loss: 0.0078
Epoch 7000, Loss: 0.0078
Epoch 7500, Loss: 0.0078
Epoch 8000, Loss: 0.0078
Epoch 8500, Loss: 0.0077
Epoch 9000, Loss: 0.0077
Epoch 9500, Loss: 0.0077
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

Predicted outputs:
 tf.Tensor(
[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]], shape=(10, 1), dtype=float32)


In [42]:
import pandas as pd
import numpy as np
from pandas import ExcelWriter

In [35]:
#changing the tensor file into list

Np = X.numpy()
x1 = Np[:,0].tolist()
x2 = Np[:,1].tolist()

Y = y.numpy()
tar = Y[:,0].tolist()


In [48]:
# for saving the data into excel file

data = {
    'input 1' : x1 ,
    'input 2' : x2,
    'taget' : tar }
    
loss_data = {    
    'torch_itration' : no_of_itration ,
    'torch_loss': list_of_loss ,
    'tensor_itration' : tf_no_of_itration ,
    'tensor_loss' : tf_list_of_loss
    
}
df = pd.DataFrame(data)
df_loss = pd.DataFrame(loss_data)
with ExcelWriter('Assignent_Target.xlsx') as writer:
    df.to_excel(writer, sheet_name='Sheet1', index=False)
    df_loss.to_excel(writer, sheet_name='Sheet2', index=False)


In [68]:
# now importing data from excel file and applying the ANN


imp_data = pd.read_excel('Assignent_Target.xlsx' , sheet_name = 'Sheet1')
x_combined = imp_data[['input 1','input 2']].values
y_data = imp_data[['taget']].values


x_torch = torch.tensor(x_combined, dtype = torch.float32)
y_torch = torch.tensor(y, dtype = torch.float32)

x_tensor = tf.convert_to_tensor(x_combined , dtype = tf.float32)
y_tensor = tf.convert_to_tensor(y_data , dtype = tf.float32)

x_torch


tensor([[0.2100, 0.2100],
        [0.1800, 0.1200],
        [0.1500, 0.1000],
        [0.1200, 0.0800],
        [0.1000, 0.0700],
        [0.0800, 0.0600],
        [0.0700, 0.0500],
        [0.0500, 0.0400],
        [0.0400, 0.0300],
        [0.0300, 0.0200]])

In [65]:
# Define the neural network model
class XORModel(nn.Module):
    def __init__(self):
        super(XORModel, self).__init__()
        self.hidden = nn.Linear(2, 4)  # 2 input features, 4 hidden units
        self.output = nn.Linear(4, 10)  # 1 output unit

    def forward(self, x):
        xh = torch.sigmoid(self.hidden(x))
        xo = (self.output(xh))
        return xo

# Instantiate the model, define the loss function and optimizer
model = XORModel()
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

# Training loop
epochs = 10000
for epoch in range(epochs):
    optimizer.zero_grad()
    outputs = model(x_torch)
    loss = criterion(outputs, y_torch)
    loss.backward()
    optimizer.step()

    if epoch % 500 == 0:
        print(f'Epoch [{epoch}/{epochs}], Loss: {loss.item():.4f}')

# Testing the model
with torch.no_grad():
    predicted = model(x_torch)
    print("Predicted outputs:\n", predicted.round())


C:\Users\qasim\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\loss.py:626: UserWarning: Using a target size (torch.Size([10, 1])) that is different to the input size (torch.Size([10, 10])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Epoch [0/10000], Loss: 35.9502
Epoch [500/10000], Loss: 4.8045
Epoch [1000/10000], Loss: 0.8439
Epoch [1500/10000], Loss: 0.1381
Epoch [2000/10000], Loss: 0.0550
Epoch [2500/10000], Loss: 0.0332
Epoch [3000/10000], Loss: 0.0230
Epoch [3500/10000], Loss: 0.0176
Epoch [4000/10000], Loss: 0.0146
Epoch [4500/10000], Loss: 0.0128
Epoch [5000/10000], Loss: 0.0118
Epoch [5500/10000], Loss: 0.0111
Epoch [6000/10000], Loss: 0.0107
Epoch [6500/10000], Loss: 0.0104
Epoch [7000/10000], Loss: 0.0102
Epoch [7500/10000], Loss: 0.0100
Epoch [8000/10000], Loss: 0.0099
Epoch [8500/10000], Loss: 0.0098
Epoch [9000/10000], Loss: 0.0097
Epoch [9500/10000], Loss: 0.0096
Predicted outputs:
 tensor([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,

In [69]:
# Define the neural network model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(4, input_shape=(2,), activation='sigmoid'),  # 4 hidden units
    tf.keras.layers.Dense(1)  # 1 output unit
])
# Compile the model
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.1), loss='mse')
# Custom callback to print the loss every 500 epochs
class PrintLoss(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
        if epoch % 500 == 0:
            print(f"Epoch {epoch}, Loss: {logs['loss']:.4f}")
# Train the model with the custom callback
model.fit(x_tensor, y_tensor, epochs=10000, verbose=0, callbacks=[PrintLoss()])
# Testing the model
predicted = model.predict(x_tensor)
print("\nPredicted outputs:\n", tf.round(predicted))

C:\Users\qasim\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 0, Loss: 46.0071
Epoch 500, Loss: 0.2518
Epoch 1000, Loss: 0.0639
Epoch 1500, Loss: 0.0287
Epoch 2000, Loss: 0.0163
Epoch 2500, Loss: 0.0114
Epoch 3000, Loss: 0.0093
Epoch 3500, Loss: 0.0084
Epoch 4000, Loss: 0.0080
Epoch 4500, Loss: 0.0078
Epoch 5000, Loss: 0.0077
Epoch 5500, Loss: 0.0077
Epoch 6000, Loss: 0.0076
Epoch 6500, Loss: 0.0076
Epoch 7000, Loss: 0.0076
Epoch 7500, Loss: 0.0076
Epoch 8000, Loss: 0.0076
Epoch 8500, Loss: 0.0076
Epoch 9000, Loss: 0.0076
Epoch 9500, Loss: 0.0076
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step

Predicted outputs:
 tf.Tensor(
[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]], shape=(10, 1), dtype=float32)
